dataset:
  class_path: "torchvision.datasets.CIFAR10"
  init_args:
    root: './cifar10'
    download: true
datamodule:
  class_path: "src.example.example_datamodule.ExampleDataModule"
  init_args:
    batch_size: 40
    shuffle: true
    device: "gpu"
    num_workers: 10
experiment:
  class_path: "thunder.experiments.abstract_experiment.AbstractExperiment"
model:
  class_path: "src.example.example_model.ExampleModel"
  init_args:
    num_classes: 10
pl_model:
  class_path: "src.example.example_pl_model.ExamplePlModel"
  init_args:
    lr: 1e-3
    optimizer_name: "Adam"
    loss_name: "CrossEntropy"
    num_classes: 10
trainer:
  class_path: "lightning.Trainer"
  init_args:
    accelerator: "gpu"